### ISSUE TITLE
AWS SNS seems to be broken with Camel 3.9 and above

### ISSUE THREAD

**Issue by orpiske** [apache/camel-kafka-connector#1156]
Failure on Apache CI: https://ci-builds.apache.org/job/Camel/job/Camel-Kafka-Connector%20Daily/job/main/4/testReport/org.apache.camel.kafkaconnector.aws.v2.sns.sink/CamelSinkAWSSNSITCase/testBasicSendReceiveUsingKafkaStyle/

Short exception snippet: 

```
Caused by: software.amazon.awssdk.services.sns.model.SnsException: null (Service: Sns, Status Code: 404, Request ID: 7a62c49f-347e-4fc4-9331-6e8eEXAMPLE, Extended Request ID: null)
        ...
        at software.amazon.awssdk.services.sns.DefaultSnsClient.subscribe(DefaultSnsClient.java:2555) ~[sns-2.16.46.jar:?]
        at org.apache.camel.component.aws2.sns.Sns2Endpoint.doInit(Sns2Endpoint.java:177) ~[camel-aws2-sns-3.10.0-SNAPSHOT.jar:3.10.0-SNAPSHOT]
        at org.apache.camel.support.service.BaseService.init(BaseService.java:83) ~[camel-api-3.10.0-SNAPSHOT.jar:3.10.0-SNAPSHOT]
        at org.apache.camel.support.service.ServiceHelper.initService(ServiceHelper.java:84) ~[camel-api-3.10.0-SNAPSHOT.jar:3.10.0-SNAPSHOT]
        at org.apache.camel.impl.engine.AbstractCamelContext.internalAddService(AbstractCamelContext.java:1441) ~[camel-base-engine-3.10.0-SNAPSHOT.jar:3.10.0-SNAPSHOT]
        at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1383) ~[camel-base-engine-3.10.0-SNAPSHOT.jar:3.10.0-SNAPSHOT]
        at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1378) ~[camel-base-engine-3.10.0-SNAPSHOT.jar:3.10.0-SNAPSHOT]
        at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1373) ~[camel-base-engine-3.10.0-SNAPSHOT.jar:3.10.0-SNAPSHOT]
        at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:946) ~[camel-base-engine-3.10.0-SNAPSHOT.jar:3.10.0-SNAPSHOT]
```

Seems to be caused when the AWS SNS SDK fails to subscribe to the queue.

**Comment by oscerd** [comment]
Auticreation is false by default now

**Comment by orpiske** [comment]
> Auticreation is false by default now

Thanks! I will investigate further tomorrow ... I ran a quick test w/ auto create, but it still had the problem.

**Comment by oscerd** [comment]
On plain camel seems to work fine

**Comment by orpiske** [comment]
> On plain camel seems to work fine

I think it may be related to the `subscribeSNStoSQS`. I don't think we have any integration test covering that on Camel Core.

**Comment by oscerd** [comment]
@orpiske no we don't. Btw the auticreation on sqs is false by default as well

**Comment by orpiske** [comment]
> @orpiske no we don't. Btw the auticreation on sqs is false by default as well

Oh, thanks for the heads up about this one as well! I am also seeing some failures with SQS, so it could be related.

**Comment by orpiske** [comment]
> On plain camel seems to work fine

You were right. Yesterday I made a mistake when trying it on Camel Core, which is why I thought there was a problem. But it turns out just adding the auto create topic option solves the problem :). Thanks!
