### ISSUE TITLE
One file per message (kafka hdfs sink connector)

### ISSUE THREAD

**Issue by FernandoDorado** [apache/camel-kafka-connector#1222]
Hello, 
I'm trying to connect kafka and hdfs to store data. I set it up and it works correctly, but the problem arises when I save the kafka messages in hdfs as a file is created for each message. I would like to create a file containing multiple messages, but I can't solve this problem. I've change the value of 
`
camel.sink.endpoint.splitStrategy=BYTES:1000000
`
`
camel.sink.endpoint.splitStrategy=MESSAGES:10
`
But when I view the files in the hdfs folder, I see one file for each message. The full configuration is as follows:

`
name=CamelHdfsSinkConnector 
`
`connector.class=org.apache.camel.kafkaconnector.hdfs.CamelHdfsSinkConnector`
`tasks.max=1`
`key.converter=org.apache.kafka.connect.storage.StringConverter`
`value.converter=org.apache.kafka.connect.storage.StringConverter`
`topics=modbus-office-topic`
`camel.sink.path.hostName=namenode`
`camel.sink.path.port=9000`
`camel.sink.endpoint.splitStrategy=BYTES:10000000`
`camel.sink.path.path=Example_folder`

I am currently running hadoop version 3.2.1, I have my doubts that this is the problem, and I don't know if the problem is with the connector, the hadoop version or the connection configuration.
Thanks for your time

**Comment by oscerd** [comment]
Please post the full configuration so we can check

**Comment by FernandoDorado** [comment]
Added to the previous comment. Thanks

**Comment by oscerd** [comment]
Can you try with

camel.sink.endpoint.append = true

**Comment by FernandoDorado** [comment]
By using this command, the connector report the following error: 


org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:609)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:329)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:182)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.connect.errors.ConnectException: Exchange delivery has failed!
	at org.apache.camel.kafkaconnector.CamelSinkTask.put(CamelSinkTask.java:199)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
	... 10 more
Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: hdfs://namenode:9000/Example_folder?append+=+true due to: Failed to resolve endpoint: hdfs://namenode:9000/Example_folder?append+=+true due to: There are 1 parameters that couldn't be set on the endpoint. Check the uri if the parameters are spelt correctly and that they are properties of the endpoint. Unknown parameters=[{append = true}]
	at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:962)
	at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:853)
	at org.apache.camel.support.CamelContextHelper.getMandatoryEndpoint(CamelContextHelper.java:73)
	at org.apache.camel.support.ExchangeHelper.resolveEndpoint(ExchangeHelper.java:120)
	at org.apache.camel.support.ExchangeHelper.resolveEndpoint(ExchangeHelper.java:99)
	at org.apache.camel.processor.SendDynamicProcessor.resolveEndpoint(SendDynamicProcessor.java:296)
	at org.apache.camel.processor.SendDynamicProcessor.process(SendDynamicProcessor.java:157)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:463)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:179)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:64)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:184)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:398)
	at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:96)
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:217)
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor$1.process(SharedCamelInternalProcessor.java:111)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:108)
	at org.apache.camel.support.cache.DefaultProducerCache.send(DefaultProducerCache.java:190)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:176)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:148)
	at org.apache.camel.kafkaconnector.CamelSinkTask.put(CamelSinkTask.java:194)
	... 11 more
Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: hdfs://namenode:9000/Example_folder?append+=+true due to: There are 1 parameters that couldn't be set on the endpoint. Check the uri if the parameters are spelt correctly and that they are properties of the endpoint. Unknown parameters=[{append = true}]
	at org.apache.camel.support.DefaultComponent.validateParameters(DefaultComponent.java:299)
	at org.apache.camel.support.DefaultComponent.createEndpoint(DefaultComponent.java:192)
	at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:928)
	... 31 more

This is the configuration that I try:

`name=CamelHdfsSinkConnector`
`connector.class=org.apache.camel.kafkaconnector.hdfs.CamelHdfsSinkConnector`
`tasks.max=1`
`key.converter=org.apache.kafka.connect.storage.StringConverter`
`value.converter=org.apache.kafka.connect.storage.StringConverter`
`topics=modbus-office-topic`
`camel.sink.path.hostName=namenode`
`camel.sink.path.port=9000`
`camel.sink.endpoint.splitStrategy=BYTES:1000000`
`camel.sink.endpoint.append = true`
`camel.sink.path.path=Example_folder`

**Comment by oscerd** [comment]
please add

camel.sink.endpoint.append=true

without spaces.

**Comment by FernandoDorado** [comment]
Sorry for the mistake, I added previously without spaces.
I tested by using the previous configuration, and it is provides an error:
org.apache.camel.FailedToCreateProducerException: Failed to create Producer for endpoint: hdfs://namenode:9000/Example_folder?append=true&splitStrategy=BYTES:1000000. Reason: java.lang.IllegalArgumentException: Split Strategies incompatible with append=true
at org.apache.camel.support.cache.DefaultProducerCache.acquireProducer(DefaultProducerCache.java:155)


When I comment `#camel.sink.endpoint.splitStrategy=BYTES:1000000` and I set `camel.sink.endpoint.append=True` the error is as follows:
Caused by: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.hdfs.protocol.AlreadyBeingCreatedException): Failed to APPEND_FILE /Example_folder.opened for DFSClient_NONMAPREDUCE_1274143120_155 on 172.18.0.18 because DFSClient_NONMAPREDUCE_1274143120_155 is already the current lease holder.

On the other hand, what I would like is to have several files of a fixed size, instead of one that keeps growing, I guess that the splitStrategy option must be present, is it so?

**Comment by oscerd** [comment]
We need to reproduce this scenario.

Can you set up a github repository with steps to reproduce and setting up the infra?

**Comment by FernandoDorado** [comment]
The repository is confidential and is part of a large architecture. To share it I have to discuss it with my superiors, as it uses compromised data and software elements, and I am not sure they can give me access. Really, it's nothing more than taking data from a data-source, storing it in a topic, and saving it in an hdfs folder. The hadoop image is this: The hadoop image we use is this: image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8. The kafka image: image: 'bitnami/kafka:latest'. Sorry I can't give more information at the moment, I will contact my superiors to notify you of the problem. In the case that it was not possible to share the data, we will keep trying with the next versions of the connector, to see if the problem is solved, as we have tried all possible configuration combinations and we have not been successful using these images. 

Thank you very much for your time in reviewing the problem and for your quick response to the problem

**Comment by oscerd** [comment]
I'll try to have a look and reproduce on my side

**Comment by FernandoDorado** [comment]
I really appreciate, if you need anything or have any questions feel free to write to me and I will send you everything you need (in case that I can share)

**Comment by FernandoDorado** [comment]
Good afternoon, 
is there any update on the issue? so far, we have not been able to solve the problem, and a file is created for each kafka message, which leads to a lot of blocks in HDFS

Thanks

**Comment by oscerd** [comment]
I didn't have the time to look at this. Sorry.

**Comment by oscerd** [comment]
I'm trying to find some time for this, sorry @FernandoDorado

**Comment by FernandoDorado** [comment]
We are still interested, if you need any more details do not hesitate to ask and I will share some details

**Comment by FernandoDorado** [comment]
The problem has been solved by using IDLE, instead of SIZE or MESSAGES. We have not been able to get it to work using the latter two.

**Comment by oscerd** [comment]
Thanks for reporting and sorry for the lack of time.
