### ISSUE TITLE
vertx websocket source kafka connector configuration

### ISSUE THREAD

**Issue by arickbro** [apache/camel-kafka-connector#1249]
Hi

I got this error when configuring the vertx websocket kafka connector 
https://camel.apache.org/camel-kafka-connector/latest/reference/connectors/camel-atmosphere-websocket-kafka-source-connector.html

may I know whether I missing any jar file here ?

```
Caused by: org.apache.camel.FailedToCreateRouteException: Failed to create route route7: Route(route7)[From[vertx-websocket/192.168.56.111:8000/] -> ... because of No endpoint could be found for: vertx-websocket/192.168.56.111://8000/, please check your classpath contains the needed Camel component jar.
        at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:80)
        at org.apache.camel.impl.DefaultModelReifierFactory.createRoute(DefaultModelReifierFactory.java:49)
        at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:826)
        at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:716)
        at org.apache.camel.impl.engine.AbstractCamelContext.doInit(AbstractCamelContext.java:2756)
        at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
        at org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2475)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:111)
        at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2494)
        at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:245)
        at org.apache.camel.main.SimpleMain.doStart(SimpleMain.java:43)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
        at org.apache.camel.kafkaconnector.CamelSourceTask.start(CamelSourceTask.java:173)
        ... 8 more

```

this is the jar under kafka connect lib path

```
annotations-13.0.jar                               camel-vertx-websocket-kafka-connector-0.10.0.jar  netty-codec-http-4.1.54.Final.jar
apicurio-registry-common-1.3.2.Final.jar           commons-compress-1.20.jar                         netty-codec-socks-4.1.54.Final.jar
apicurio-registry-rest-client-1.3.2.Final.jar      connect-json-2.6.0.jar                            netty-common-4.1.54.Final.jar
apicurio-registry-utils-converter-1.3.2.Final.jar  converter-jackson-2.9.0.jar                       netty-handler-4.1.54.Final.jar
apicurio-registry-utils-serde-1.3.2.Final.jar      jackson-annotations-2.12.3.jar                    netty-handler-proxy-4.1.54.Final.jar
avro-1.10.2.jar                                    jackson-core-2.12.3.jar                           netty-resolver-4.1.54.Final.jar
camel-api-3.10.0.jar                               jackson-databind-2.12.3.jar                       netty-resolver-dns-4.1.54.Final.jar
camel-base-3.10.0.jar                              jackson-dataformat-avro-2.11.3.jar                netty-transport-4.1.54.Final.jar
camel-base-engine-3.10.0.jar                       jackson-datatype-jdk8-2.11.3.jar                  NOTICE.txt
camel-core-engine-3.10.0.jar                       javax.annotation-api-1.3.2.jar                    okhttp-4.8.1.jar
camel-core-languages-3.10.0.jar                    jboss-jaxrs-api_2.1_spec-2.0.1.Final.jar          okio-2.7.0.jar
camel-core-model-3.10.0.jar                        jctools-core-3.3.0.jar                            protobuf-java-3.13.0.jar
camel-core-processor-3.10.0.jar                    kafka-clients-2.8.0.jar                           README.adoc
camel-core-reifier-3.10.0.jar                      kotlin-reflect-1.3.20.jar                         retrofit-2.9.0.jar
camel-direct-3.10.0.jar                            kotlin-stdlib-1.3.20.jar                          slf4j-api-1.7.30.jar
camel-jackson-3.10.0.jar                           kotlin-stdlib-common-1.3.20.jar                   snappy-java-1.1.8.1.jar
camel-kafka-3.10.0.jar                             LICENSE.txt                                       vertx-auth-common-4.0.3.jar
camel-kafka-connector-0.10.0.jar                   lz4-java-1.7.1.jar                                vertx-bridge-common-4.0.3.jar
camel-main-3.10.0.jar                              medeia-validator-core-1.1.1.jar                   vertx-core-4.0.3.jar
camel-management-api-3.10.0.jar                    medeia-validator-jackson-1.1.1.jar                vertx-web-4.0.3.jar
camel-seda-3.10.0.jar                              netty-buffer-4.1.54.Final.jar                     vertx-web-common-4.0.3.jar
camel-support-3.10.0.jar                           netty-codec-4.1.54.Final.jar                      zstd-jni-1.4.9-1.jar
camel-util-3.10.0.jar                              netty-codec-dns-4.1.54.Final.jar
camel-vertx-websocket-3.10.0.jar                   netty-codec-http2-4.1.54.Final.jar
```

**Comment by oscerd** [comment]
It needs to be exploded in a single folder in the Kafka connector plugin path

**Comment by oscerd** [comment]
I think this is in the root folder only

**Comment by arickbro** [comment]
Hi

this inside the folder, I manage to make camel-ahc-ws-kafka-connector  and camel-websocket-jsr356-kafka-connector but not the camel-vertx-websocket-kafka-connector  

```
camel-ahc-ws-kafka-connector                                     
camel-ahc-wss-kafka-connector                                     camel-websocket-jsr356-kafka-connector
camel-atmosphere-websocket-kafka-connector                        camel-websocket-kafka-connector
camel-vertx-websocket-kafka-connector                             docs
```
