### ISSUE TITLE
how to convert csv to json using unmarshal/marshal 

### ISSUE THREAD

**Issue by arickbro** [apache/camel-kafka-connector#1253]
I try to ingest a csv file using camel sftp connector , parse the csv and turn it to json using this configuration

```
{
	"connector.class":"org.apache.camel.kafkaconnector.sftp.CamelSftpSourceConnector",
	"topics":"sftp3",
	"tasks.max":"1",
	"key.converter":"org.apache.kafka.connect.converters.ByteArrayConverter",
	"value.converter":"org.apache.kafka.connect.storage.StringConverter",
	"errors.tolerance":"none",
	"camel.source.path.host":"10.0.2.111",
	"camel.source.path.port":"22",
	"camel.source.path.directoryName":"demos/simlink",
	"camel.source.path.fileName":"bgp.txt",
	"camel.source.endpoint.recursive":"false",
	"camel.source.endpoint.username":"xxx",
	"camel.source.endpoint.password":"xxxx",
	"camel.source.endpoint.noop":"true",
	"transforms":"RemoteTransformer",
	"transforms.RemoteTransformer.type":"org.apache.camel.kafkaconnector.RemoteFileTransforms",
	"camel.source.endpoint.idempotentKey":"${file:name}-${file:modified}",
	"camel.remove.headers.pattern":"Camel*",
	"camel.source.marshal":"json-gson",
	"camel.source.unmarshal":"csv"
}
```

**unmarshal=csv** work just fine, I can see the java object on kafka.
but if I combine it with **marshal=json-gson**, I got this error 
```
 (org.apache.camel.processor.errorhandler.DefaultErrorHandler)
java.lang.IllegalStateException: IOException reading next record: java.io.IOException: (line 1) invalid char between encapsulated token and delimiter
        at org.apache.commons.csv.CSVParser$CSVRecordIterator.getNextRecord(CSVParser.java:149)
        at org.apache.commons.csv.CSVParser$CSVRecordIterator.hasNext(CSVParser.java:159)
```

could someone give me advise on this ?

**Comment by oscerd** [comment]
You cannot have unmarshal and marshal in the same connector configuration. If you want to do this you'll need to create your own SMT to transform from csv to JSON.

**Comment by arickbro** [comment]
thanks, I will close this issue
