### ISSUE TITLE
Custom kafkaconnetor class as CamelAws2s3SourceConnector

### ISSUE THREAD

**Issue by ruchirvaninasdaq** [apache/camel-kafka-connector#1285]
Hello, 
I have added a custom class extending CamelAws2S3SourceConnector for some custom work. Now trying to build the project and deploy it. It's giving me the following error 

I am using 0.7.x branch `https://github.com/apache/camel-kafka-connector/tree/camel-kafka-connector-0.7.x` on Strimzi 0.25.0 cluster.

```
2021-11-09 16:00:21,642 INFO Creating connector my-connector of type org.apache.camel.kafkaconnector.aws2s3.CamelAws2s3SourceConnector (org.apache.kafka.connect.runtime.Worker) [StartAndStopExecutor-connect-1-1]
2021-11-09 16:00:21,643 ERROR Failed to start connector my-connector (org.apache.kafka.connect.runtime.Worker) [StartAndStopExecutor-connect-1-1]
org.apache.kafka.connect.errors.ConnectException: Failed to find any class that implements Connector and which name matches org.apache.camel.kafkaconnector.aws2s3.CamelAws2s3SourceConnector, available connectors are: PluginDesc{klass=class com.nasdaq.ncds.kafkaconnector.common.CamelSinkConnector, name='com.nasdaq.ncds.kafkaconnector.common.CamelSinkConnector', version='null', encodedVersion=null, type=sink, typeName='sink', location='file:/opt/kafka/plugins/my-connector/'}, PluginDesc{klass=class com.nasdaq.ncds.kafkaconnector.common.CamelSourceConnector, name='com.nasdaq.ncds.kafkaconnector.common.CamelSourceConnector', version='null', encodedVersion=null, type=source, typeName='source', location='file:/opt/kafka/plugins/my-connector/'}, PluginDesc{klass=class com.nasdaq.ncds.kafkaconnector.s3.CamelAws2s3SourceConnector, name='com.nasdaq.ncds.kafkaconnector.s3.CamelAws2s3SourceConnector', version='null', encodedVersion=null, type=source, typeName='source', location='file:/opt/kafka/plugins/my-connector/'}, PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSinkConnector, name='org.apache.kafka.connect.file.FileStreamSinkConnector', version='2.8.0', encodedVersion=2.8.0, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSourceConnector, name='org.apache.kafka.connect.file.FileStreamSourceConnector', version='2.8.0', encodedVersion=2.8.0, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorCheckpointConnector, name='org.apache.kafka.connect.mirror.MirrorCheckpointConnector', version='1', encodedVersion=1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorHeartbeatConnector, name='org.apache.kafka.connect.mirror.MirrorHeartbeatConnector', version='1', encodedVersion=1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorSourceConnector, name='org.apache.kafka.connect.mirror.MirrorSourceConnector', version='1', encodedVersion=1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockConnector, name='org.apache.kafka.connect.tools.MockConnector', version='2.8.0', encodedVersion=2.8.0, type=connector, typeName='connector', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='2.8.0', encodedVersion=2.8.0, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnector', version='2.8.0', encodedVersion=2.8.0, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='2.8.0', encodedVersion=2.8.0, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConnector', version='2.8.0', encodedVersion=2.8.0, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='2.8.0', encodedVersion=2.8.0, type=source, typeName='source', location='classpath'}
	at org.apache.kafka.connect.runtime.isolation.Plugins.connectorClass(Plugins.java:208)
	at org.apache.kafka.connect.runtime.isolation.Plugins.newConnector(Plugins.java:180)
	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:275)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1348)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$getConnectorStartingCallable$22(DistributedHerder.java:1354)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-11-09 16:00:21,645 ERROR Failed to start task my-connector-0 (org.apache.kafka.connect.runtime.Worker) [StartAndStopExecutor-connect-1-2]
org.apache.kafka.common.config.ConfigException: Invalid value org.apache.camel.kafkaconnector.aws2s3.converters.S3ObjectConverter for configuration value.converter: Class org.apache.camel.kafkaconnector.aws2s3.converters.S3ObjectConverter could not be found.
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:744)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:490)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:483)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:129)
	at org.apache.kafka.connect.runtime.ConnectorConfig.<init>(ConnectorConfig.java:230)
	at org.apache.kafka.connect.runtime.ConnectorConfig.<init>(ConnectorConfig.java:226)
	at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:520)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1287)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$getTaskStartingCallable$17(DistributedHerder.java:1300)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

I have verified that my configs are applied. 

kubectl get kafkaconnector my-connector -o yaml

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kafka.strimzi.io/v1beta2","kind":"KafkaConnector","metadata":{"annotations":{},"labels":{"strimzi.io/cluster":"my-kafka-connect-cluster"},"name":"my-connector","namespace":"myns"},"spec":{"class":"com.nasdaq.ncds.kafkaconnector.s3.CamelAws2s3SourceConnector","config":{"camel.component.aws2-s3.autocloseBody":false,"camel.component.aws2-s3.includeBody":true,"camel.component.aws2-s3.useDefaultCredentialsProvider":true,"camel.source.endpoint.destinationBucket":"bucket","camel.source.endpoint.moveAfterRead":true,"camel.source.endpoint.useDefaultCredentialsProvider":true,"camel.source.kafka.topic":"data","camel.source.maxBatchPollSize":1000,"camel.source.maxPollDuration":10,"camel.source.path.bucketNameOrArn":"bucketuinput","client.id":"client","connector.class":"com.nasdaq.ncds.kafkaconnector.s3.CamelAws2s3SourceConnector","key.converter":"org.apache.kafka.connect.storage.StringConverter","topics":"data","value.converter":"com.nasdaq.ncds.kafkaconnector.s3.converters.S3ObjectConverter"},"tasksMax":1}}
  creationTimestamp: "2021-11-09T15:55:43Z"
  generation: 1
  labels:
    strimzi.io/cluster: my-kafka-connect-cluster
  name: my-connector
  namespace: ns
  resourceVersion: "225638895"
  selfLink: /apis/kafka.strimzi.io/v1beta2/namespaces/ns/kafkaconnectors/my-connector
  uid: c408cd1c-7985-473f-9f48-7f8addf2fd22
spec:
  class: com.nasdaq.ncds.kafkaconnector.s3.CamelAws2s3SourceConnector
  config:
    camel.component.aws2-s3.autocloseBody: false
    camel.component.aws2-s3.includeBody: true
    camel.component.aws2-s3.useDefaultCredentialsProvider: true
    camel.source.endpoint.destinationBucket: bucket
    camel.source.endpoint.moveAfterRead: true
    camel.source.endpoint.useDefaultCredentialsProvider: true
    camel.source.kafka.topic: data
    camel.source.maxBatchPollSize: 1000
    camel.source.maxPollDuration: 10
    camel.source.path.bucketNameOrArn: bucket
    client.id:client
    connector.class: com.nasdaq.ncds.kafkaconnector.s3.CamelAws2s3SourceConnector
    key.converter: org.apache.kafka.connect.storage.StringConverter
    topics: data
    value.converter: com.nasdaq.ncds.kafkaconnector.s3.converters.S3ObjectConverter
  tasksMax: 1
status:
  conditions:
  - lastTransitionTime: "2021-11-09T15:55:59.577283Z"
    message: 'GET /connectors/my-connector/config returned 500 (Internal Server
      Error): Failed to find any class that implements Connector and which name matches
      org.apache.camel.kafkaconnector.aws2s3.CamelAws2s3SourceConnector, available
      connectors are: PluginDesc{klass=class com.nasdaq.ncds.kafkaconnector.common.CamelSinkConnector,
      name=''com.nasdaq.ncds.kafkaconnector.common.CamelSinkConnector'', version=''null'',
      encodedVersion=null, type=sink, typeName=''sink'', location=''file:/opt/kafka/plugins/my-connector/''},
      PluginDesc{klass=class com.nasdaq.ncds.kafkaconnector.common.CamelSourceConnector,
      name=''com.nasdaq.ncds.kafkaconnector.common.CamelSourceConnector'', version=''null'',
      encodedVersion=null, type=source, typeName=''source'', location=''file:/opt/kafka/plugins/my-connector/''},
      PluginDesc{klass=class com.nasdaq.ncds.kafkaconnector.s3.CamelAws2s3SourceConnector,
      name=''com.nasdaq.ncds.kafkaconnector.s3.CamelAws2s3SourceConnector'', version=''null'',
      encodedVersion=null, type=source, typeName=''source'', location=''file:/opt/kafka/plugins/my-connector/''},
      PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSinkConnector,
      name=''org.apache.kafka.connect.file.FileStreamSinkConnector'', version=''2.8.0'',
      encodedVersion=2.8.0, type=sink, typeName=''sink'', location=''classpath''},
      PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSourceConnector,
      name=''org.apache.kafka.connect.file.FileStreamSourceConnector'', version=''2.8.0'',
      encodedVersion=2.8.0, type=source, typeName=''source'', location=''classpath''},
      PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorCheckpointConnector,
      name=''org.apache.kafka.connect.mirror.MirrorCheckpointConnector'', version=''1'',
      encodedVersion=1, type=source, typeName=''source'', location=''classpath''},
      PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorHeartbeatConnector,
      name=''org.apache.kafka.connect.mirror.MirrorHeartbeatConnector'', version=''1'',
      encodedVersion=1, type=source, typeName=''source'', location=''classpath''},
      PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorSourceConnector,
      name=''org.apache.kafka.connect.mirror.MirrorSourceConnector'', version=''1'',
      encodedVersion=1, type=source, typeName=''source'', location=''classpath''},
      PluginDesc{klass=class org.apache.kafka.connect.tools.MockConnector, name=''org.apache.kafka.connect.tools.MockConnector'',
      version=''2.8.0'', encodedVersion=2.8.0, type=connector, typeName=''connector'',
      location=''classpath''}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector,
      name=''org.apache.kafka.connect.tools.MockSinkConnector'', version=''2.8.0'',
      encodedVersion=2.8.0, type=sink, typeName=''sink'', location=''classpath''},
      PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name=''org.apache.kafka.connect.tools.MockSourceConnector'',
      version=''2.8.0'', encodedVersion=2.8.0, type=source, typeName=''source'', location=''classpath''},
      PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector,
      name=''org.apache.kafka.connect.tools.SchemaSourceConnector'', version=''2.8.0'',
      encodedVersion=2.8.0, type=source, typeName=''source'', location=''classpath''},
      PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector,
      name=''org.apache.kafka.connect.tools.VerifiableSinkConnector'', version=''2.8.0'',
      encodedVersion=2.8.0, type=source, typeName=''source'', location=''classpath''},
      PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector,
      name=''org.apache.kafka.connect.tools.VerifiableSourceConnector'', version=''2.8.0'',
      encodedVersion=2.8.0, type=source, typeName=''source'', location=''classpath''}'
    reason: ConnectRestException
    status: "True"
    type: NotReady
  observedGeneration: 1
  tasksMax: 1
  topics: []
```

Please let me know if you need any more information.

**Comment by ruchirvaninasdaq** [comment]
BDW, If I move my all code from `com.nasdaq.ncds.kafkaconnector.s3.CamelAws2s3SourceConnector` to `org.apache.camel.kafkaconnector.aws2s3.CamelAws2s3SourceConnector` it works. So Something I am missing in configuration.

**Comment by ruchirvaninasdaq** [comment]
Something more I see in logs 
```2021-11-09 16:00:21,641 INFO Creating task my-connector-0 (org.apache.kafka.connect.runtime.Worker) [StartAndStopExecutor-connect-1-2]
2021-11-09 16:00:21,642 INFO Creating connector my-connector of type org.apache.camel.kafkaconnector.aws2s3.CamelAws2s3SourceConnector (org.apache.kafka.connect.runtime.Worker) [StartAndStopExecutor-connect-1-1]
```

I am not sure why it shows like that as I am setting connecttor class as my class `com.nasdaq.ncds.kafkaconnector.s3.CamelAws2s3SourceConnector`

**Comment by oscerd** [comment]
I think it's really hard to say something without looking at the connector structure.
By the way, it makes sense to create a completely new connector instead of extending a new one if you have to do something. Extending a connector from ckc means adding something like SMT or converters or modify the existing code of the connector, we never meant to extend the connector class even though it should be feasible.

**Comment by ruchirvaninasdaq** [comment]
![Screen Shot 2021-11-10 at 8 58 23 AM](https://user-images.githubusercontent.com/32844383/141126691-39f04435-4628-46ff-861b-8f4b1619c1af.png)

**Comment by ruchirvaninasdaq** [comment]
So I have updated the Camel sourceconnector here to my custom class which is as follows.

```public class NcdsCamelAws2s3SourceConnector extends CamelSourceConnector {

    private static final Logger LOG = LoggerFactory.getLogger(NcdsCamelAws2s3SourceConnector.class);
    @Override
    public ConfigDef config() {
        return CamelAws2s3SourceConnectorConfig.conf();
    }
    @Override
    public Class<? extends Task> taskClass() {
        return CamelAws2s3SourceTask.class;
    }
    // Some customcode 
}```

**Comment by oscerd** [comment]
Not sure about this particular use cases. Probably it's something in the core.

**Comment by ruchirvaninasdaq** [comment]
Core is added in common package.

**Comment by ruchirvaninasdaq** [comment]
So. if I dont change the package and add my custom code it works. Is there anything special needs to be pulled from the build plan?

**Comment by oscerd** [comment]
> Core is added in common package.

Yes, I meant something in the core checking for a specific package like org.apache.camel...

**Comment by ruchirvaninasdaq** [comment]
Does those autogenerated properties and resources  (in generated packages) make any difference?

**Comment by oscerd** [comment]
> So. if I dont change the package and add my custom code it works. Is there anything special needs to be pulled from the build plan?

No.

**Comment by oscerd** [comment]
> Does those autogenerated properties and resources (in generated packages) make any difference?

No, they are related to the underline camel component. I don't know what is in your extended class, but I suppose you're not using the camel component any more. Probably.

**Comment by ruchirvaninasdaq** [comment]
What would be your recommended approach for customizing the s3 connector module? (Like i need to add custom seralizer, I need to start some monitoring process before starting the connector, I need to update metrics on every messages processed)

**Comment by oscerd** [comment]
Ok, so you're still using the basic feature of the connector, this means you're still using the component. My suggestion for the moment is to maintain the package name and maybe you could provide some doc about what you were doing and how.

Keep in mind that we are going to base the behavior of the connectors on kamelets from the next release. So something could change in your application if you update.

cc @valdar

**Comment by ruchirvaninasdaq** [comment]
@oscerd : It was an indeed the issue with package name. Once I moved back all common code to connector package it worked. If you can help with where this package dependency is, it would be helpful for the futre. 

For now, I have created projcts with 2 different packages. One for my custom code and other for camel connector code. Please recommend if something I need to change in future and if any migration plans documentation around migrating kameltes would very helpful.

This is the strcture of my current project.
<img width="495" alt="Screen Shot 2021-11-15 at 6 21 07 PM" src="https://user-images.githubusercontent.com/32844383/141868070-370a54eb-62fc-4f6e-bb3e-93125fd6c82d.png">

**Comment by ruchirvaninasdaq** [comment]
Following customizations I am doing withing the camel connectors: 
1. I have custom S3Object Conveter (to use my custom Seralizer)
2. I have added promethues metric collector gauge to Kafkaconnect. In camel source task I update metric with every message pull from s3. 
3. I have some initialization process on intilization of Kafkaconnect (push some message to our kafka cluster to wake up other processes). For this, I add my custom method in CamelAws2S3SourceConnector method.

I have also updated the camel-s3 for my custom reading process. I really appreciate the method/feture you added on my request for moveAfterRead. But we need more custom messagefactory class to validate the mesage even before we send to connector. So we have custom logic added in camel-s3 package also for that. 

If you have any better recommended approch please let me know.

**Comment by oscerd** [comment]
> @oscerd : Thanks you!! It was an indeed the issue with the package name. Once I moved back all common code to connector package (org.apche.camel) it worked. If you can help with where this package dependency is, it would be helpful for the futre.
> 
> For now, I have created projcts with 2 different packages. One for my custom code and other for camel connector code. Please recommend if something I need to change in future and if any migration plans documentation around migrating kameltes would very helpful.
> 
> This is the strcture of my current project. <img alt="Screen Shot 2021-11-15 at 6 21 07 PM" width="495" src="https://user-images.githubusercontent.com/32844383/141868070-370a54eb-62fc-4f6e-bb3e-93125fd6c82d.png">

The package is statically defined in the CamelKafkaConnectorUpdateMojo in the tooling part. For the moment, it cannot be customize.
