### ISSUE TITLE
SalesforceConsumer : java.lang.IllegalStateException: Queue full 

### ISSUE THREAD

**Issue by Ziauddin135** [apache/camel-kafka-connector#1342]
Hi Team,

I am using camel-kafka- source connector 0.11. to consume salesforce platform events.  I am getting below error while camel consumer consumes certain events from salesforce for replayId = -2:-

```
[2022-03-01 16:29:55,893] WARN Error processing exchange. Exchange[7D9BA2FA89D07AB-00000000000043E8]. Caused by: [java.lang.IllegalStateException - Queue full] (org.apache.camel.component.salesforce.SalesforceConsumer:214)
java.lang.IllegalStateException: Queue full
	at java.util.AbstractQueue.add(Unknown Source)
	at org.apache.camel.component.seda.SedaProducer.addToQueue(SedaProducer.java:251)
	at org.apache.camel.component.seda.SedaProducer.process(SedaProducer.java:149)
	at org.apache.camel.processor.SendDynamicProcessor.lambda$process$0(SendDynamicProcessor.java:197)
	at org.apache.camel.support.cache.DefaultProducerCache.doInAsyncProducer(DefaultProducerCache.java:318)
	at org.apache.camel.processor.SendDynamicProcessor.process(SendDynamicProcessor.java:182)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:463)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:179)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:64)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:184)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:398)
	at org.apache.camel.component.salesforce.SalesforceConsumer.processMessage(SalesforceConsumer.java:164)
	at org.apache.camel.component.salesforce.internal.streaming.SubscriptionHelper$6.onMessage(SubscriptionHelper.java:442)
	at org.cometd.common.AbstractClientSession$AbstractSessionChannel.notifyOnMessage(AbstractClientSession.java:583)
	at org.cometd.common.AbstractClientSession$AbstractSessionChannel.notifyMessageListeners(AbstractClientSession.java:574)
	at org.cometd.common.AbstractClientSession.notifyListeners(AbstractClientSession.java:308)
	at org.cometd.common.AbstractClientSession.lambda$receive$4(AbstractClientSession.java:269)
	at org.cometd.bayeux.Promise$2.succeed(Promise.java:103)
	at org.cometd.common.AsyncFoldLeft$AbstractLoop.run(AsyncFoldLeft.java:199)
	at org.cometd.common.AsyncFoldLeft.run(AsyncFoldLeft.java:93)
	at org.cometd.common.AbstractClientSession.extendIncoming(AbstractClientSession.java:103)
	at org.cometd.common.AbstractClientSession.receive(AbstractClientSession.java:263)
	at org.cometd.client.BayeuxClient.processMessage(BayeuxClient.java:798)
	at org.cometd.client.BayeuxClient.processMessages(BayeuxClient.java:621)
	at org.cometd.client.BayeuxClient.access$2000(BayeuxClient.java:101)
	at org.cometd.client.BayeuxClient$MessageTransportListener.onMessages(BayeuxClient.java:1260)
	at org.cometd.client.transport.LongPollingTransport$2.onComplete(LongPollingTransport.java:240)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:481)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:461)
	at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:424)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:365)
	at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1180)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1553)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:204)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:144)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:79)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:131)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:172)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Unknown Source)
```

following are the connecctor configuration:-

```
name=local-camel-sf-source
connector.class=org.apache.camel.kafkaconnector.salesforce.CamelSalesforceSourceConnector
camel.source.path.topicName=/event/LoginEventStream
camel.component.salesforce.clientId=<redacted>
camel.component.salesforce.clientSecret=<redacted>
camel.component.salesforce.loginUrl=<redacted>
camel.component.salesforce.userName=<redacted>
camel.component.salesforce.password=<redacted>
camel.component.salesforce.authenticationType=USERNAME_PASSWORD
camel.source.endpoint.backoffIncrement=5000
value.converter.basic.auth.credentials.source=USER_INFO
value.converter.schema.registry.basic.auth.user.info=<redacted>
camel.component.salesforce.limit=1000
camel.source.endpoint.replayId=-2
linger.ms = 5000
camel.source.maxPollDuration=500
camel.source.maxBatchPollSize = 100000
camel.source.pollingConsumerBlockTimeout=10000
camel.source.pollingConsumerBlockWhenFull=true
errors.retry.timeout=-1
camel.source.maxNotCommittedRecords=5000
tasks.max=1
topics=avrotest1232
```

Please help how i can fix this

**Comment by Ziauddin135** [comment]
Please help

**Comment by bvn13** [comment]
Seems you are using Seda queue and it is exhausted of its size. 
You can increase Seda queue size adjusting queueSize property as mentioned in docs https://camel.apache.org/components/3.15.x/seda-component.html

It is not a failure of Camel-Kafka-Connector component.

**Comment by Ziauddin135** [comment]
Thanks @bvn13 

Alongs side blockqueueWhenfull, defaultOfferTimeout, I set the mentioned property and I have not noticed any queue full error yet 

Thanks once again!

**Comment by xiaospider** [comment]
@Ziauddin135 
I meet the same problem. Can you show which properties were changed?

**Comment by Ziauddin135** [comment]
@xiaospider 

Sorry i just noticed your message. "camel.source.pollingConsumerQueueSize": "2000",
