### ISSUE TITLE
CamelSalesforcesourceSourceConnector: Failed to resolve endpoint error

### ISSUE THREAD

**Issue by mdimas** [apache/camel-kafka-connector#1433]
Given the following configuration options:
```
    "name":"contacts-from-salesforce",
    "connector.class":"org.apache.camel.kafkaconnector.salesforcesource.CamelSalesforcesourceSourceConnector",
    "tasks.max":1,
    "key.converter":"org.apache.kafka.connect.storage.StringConverter",
    "value.converter":"org.apache.kafka.connect.storage.StringConverter",
    "camel.kamelet.salesforce-source.query":"SELECT Id, Name, Email, Phone FROM Contact",
    "camel.kamelet.salesforce-source.topicName":"salesforce-contacts",
    "camel.kamelet.salesforce-source.loginUrl":"https://my--sandbox.my.salesforce.com",
    "camel.kamelet.salesforce-source.notifyForFields":"ALL",
    "camel.kamelet.salesforce-source.clientId":"CLIENT_ID",
    "camel.kamelet.salesforce-source.clientSecret":"CLIENT_SECRET",
    "camel.kamelet.salesforce-source.userName":"USER_NAME",
    "camel.kamelet.salesforce-source.password":"PASSWORD",
```
the connector is getting this error on startup:
```
Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: local-salesforce-6://salesforce-contacts?clientId=CLIENT_ID&clientSecret=xxxxxx&loginUrl=https%3A%2F%my--sandbox.my.salesforce.com&notifyForFields=ALL&notifyForOperationCreate=true&notifyForOperationDelete=false&notifyForOperationUndelete=false&notifyForOperationUpdate=false&password=xxxxxx&sObjectQuery=SELECT+Id%2C+Name%2C+Email%2C+Phone+FROM+Contact&updateTopic=true&userName=USER_NAME due to: There are 5 parameters that couldn't be set on the endpoint. Check the uri if the parameters are spelt correctly and that they are properties of the endpoint. Unknown parameters=[{clientId=CLIENT_ID, clientSecret=CLIENT_SECRET, loginUrl=https://my--sandbox.my.salesforce.com, password=PASSWORD, userName=USER_NAME}]
    at org.apache.camel.support.DefaultComponent.validateParameters(DefaultComponent.java:299)
    at org.apache.camel.support.DefaultComponent.createEndpoint(DefaultComponent.java:192)
    at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:934)
```

**Comment by mdimas** [comment]
This seems to be related to the issue highlighted here: https://stackoverflow.com/questions/72121976/camel-salesforce-kafka-source-connector-does-not-start, where it says "This type of settings should be done at component level not at endpoint level".

**Comment by oscerd** [comment]
Please try with camel-kafka-connector 3.18.1 just released. It brings in camel-kamelets 0.9.0 where there is a fix for this.

**Comment by mdimas** [comment]
Thanks, that did get me past startup. I'm now having an issue because it looks like UPDATE actions aren't being notified. It looks like this change went in after the 0.9.0 release of camel-kamelets. https://github.com/apache/camel-kamelets/commit/00b8eb7330b2c91d7597b40d6dbe8347e807adb3

**Comment by mdimas** [comment]
One more thing, for new records I am seeing a message written to Kafka, but it seems to be writing the stream object reference rather than content of the stream. For example, I get `org.apache.camel.converter.stream.InputStreamCache@47257e39` as the kafka message.

**Comment by oscerd** [comment]
For camel-kamelets 0.9.x, yes we need to release a new catalog and release a new version of camel-kafka-connector.

Not sure for second question, but this should be related: https://camel.apache.org/manual/camel-3x-upgrade-guide-3_17.html#_stream_caching

**Comment by apoorvmintri** [comment]
@oscerd @mdimas @aozmen121 
Connector version 3.18.2
#### Workaround
Add the following:
`"value.converter":"org.apache.kafka.connect.converters.ByteArrayConverter",
"camel.main.streamCachingEnabled": "false"`

Now you'll get the value as json. But I do not see the salesforce schema. Not sure if that is working as intended and requires some other property to be set.
