### ISSUE TITLE
camel https sink connector 3.18.2 NoSuchMethodError 

### ISSUE THREAD

**Issue by glew02** [apache/camel-kafka-connector#1509]
Hi

When running this connector, version 3.18.2, I'm getting this error:
```
Caused by: java.lang.NoSuchMethodError: 'boolean org.apache.camel.util.ObjectHelper.isNotEmpty(java.lang.String)'
```
For configurations, I'm just setting the uri and the httpMethod
```
  config:
    topics: {{ .Values.topics }}
    camel.sink.path.httpUri: {{ .Values.httpUri }}
    camel.sink.endpoint.httpMethod: "PUT"
 ``` 

To resolve the issue, I tried adding in the camel-core-3.18.2 jar to the same folder the connector's jars are in, but I'm still getting the exact same issue. Could you please advise what I can do to resolve this?

Thanks

Stack Trace:
```
2023-02-18 01:01:12,322 ERROR [camel-https-sink-kcr-1.0.0|task-0] Failed delivery for (MessageId: 7B3D7D65D7D2F83-0000000000000000 on ExchangeId: 7B3D7D65D7D2F83-0000000000000000). Exhausted after delivery attempt: 1 caught: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[7B3D7D65D7D2F83-0000000000000000]

Message History (complete message history is disabled)
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[route2            ] [route2            ] [                                                                              ] [        22]
	...
[ckcRemoveHeader-3 ] [toD2              ] [kamelet:ckcSink                                                               ] [         0]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
 (org.apache.camel.processor.errorhandler.DefaultErrorHandler) [task-thread-camel-https-sink-kcr-1.0.0-0]
org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[7B3D7D65D7D2F83-0000000000000000]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
	at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:589)
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
	at org.apache.camel.processor.SendDynamicProcessor.process(SendDynamicProcessor.java:170)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:469)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:187)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:64)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:184)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:398)
	at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:96)
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:217)
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor$1.process(SharedCamelInternalProcessor.java:111)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:108)
	at org.apache.camel.support.cache.DefaultProducerCache.send(DefaultProducerCache.java:199)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:176)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:148)
	at org.apache.camel.kafkaconnector.CamelSinkTask.put(CamelSinkTask.java:205)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:333)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoSuchMethodError: 'boolean org.apache.camel.util.ObjectHelper.isNotEmpty(java.lang.String)'
	at org.apache.camel.component.http.HttpEndpoint.createHttpClient(HttpEndpoint.java:232)
	at org.apache.camel.component.http.HttpEndpoint.getHttpClient(HttpEndpoint.java:201)
	at org.apache.camel.component.http.HttpProducer.<init>(HttpProducer.java:103)
	at org.apache.camel.component.http.HttpEndpoint.createProducer(HttpEndpoint.java:184)
	at org.apache.camel.support.DefaultEndpoint.createAsyncProducer(DefaultEndpoint.java:197)
	at org.apache.camel.processor.SendProcessor.doStart(SendProcessor.java:245)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:130)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler.doStart(RedeliveryErrorHandler.java:1653)
	at org.apache.camel.support.ChildServiceSupport.start(ChildServiceSupport.java:60)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:130)
	at org.apache.camel.impl.engine.DefaultChannel.doStart(DefaultChannel.java:126)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:116)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:130)
	at org.apache.camel.processor.Pipeline.doStart(Pipeline.java:221)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
	at org.apache.camel.support.processor.DelegateAsyncProcessor.doStart(DelegateAsyncProcessor.java:89)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
	at org.apache.camel.impl.engine.RouteService.startChildServices(RouteService.java:396)
	at org.apache.camel.impl.engine.RouteService.doWarmUp(RouteService.java:193)
	at org.apache.camel.impl.engine.RouteService.warmUp(RouteService.java:121)
	at org.apache.camel.impl.engine.InternalRouteStartupManager.doWarmUpRoutes(InternalRouteStartupManager.java:306)
	at org.apache.camel.impl.engine.InternalRouteStartupManager.safelyStartRouteServices(InternalRouteStartupManager.java:189)
	at org.apache.camel.impl.engine.InternalRouteStartupManager.safelyStartRouteServices(InternalRouteStartupManager.java:240)
	at org.apache.camel.impl.engine.AbstractCamelContext.startRouteService(AbstractCamelContext.java:3643)
	at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:872)
	at org.apache.camel.impl.DefaultModel.addRouteDefinitions(DefaultModel.java:185)
	at org.apache.camel.impl.DefaultModel.addRouteDefinition(DefaultModel.java:191)
	at org.apache.camel.impl.DefaultModel.addRouteFromTemplate(DefaultModel.java:415)
	at org.apache.camel.impl.DefaultModel.addRouteFromTemplate(DefaultModel.java:303)
	at org.apache.camel.impl.DefaultCamelContext.addRouteFromTemplate(DefaultCamelContext.java:433)
	at org.apache.camel.component.kamelet.KameletComponent$LifecycleHandler.createRouteForEndpoint(KameletComponent.java:401)
	at org.apache.camel.component.kamelet.KameletComponent$LifecycleHandler.track(KameletComponent.java:437)
	at org.apache.camel.component.kamelet.KameletComponent$1.doInit(KameletComponent.java:152)
	at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
	at org.apache.camel.support.service.ServiceHelper.initService(ServiceHelper.java:84)
	at org.apache.camel.impl.engine.AbstractCamelContext.internalAddService(AbstractCamelContext.java:1530)
	at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1475)
	at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1470)
	at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1465)
	at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:952)
	at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:859)
	at org.apache.camel.support.CamelContextHelper.getMandatoryEndpoint(CamelContextHelper.java:73)
	at org.apache.camel.support.ExchangeHelper.resolveEndpoint(ExchangeHelper.java:120)
	at org.apache.camel.support.ExchangeHelper.resolveEndpoint(ExchangeHelper.java:99)
	at org.apache.camel.processor.SendDynamicProcessor.resolveEndpoint(SendDynamicProcessor.java:296)
	at org.apache.camel.processor.SendDynamicProcessor.process(SendDynamicProcessor.java:157)
	... 25 more
```

**Comment by orpiske** [comment]
It is claiming not to be finding the `ObjectHelper`:

`Caused by: java.lang.NoSuchMethodError: 'boolean org.apache.camel.util.ObjectHelper.isNotEmpty(java.lang.String)'`

This is part of the `camel-util` module. Make sure you have that one with our connector.

**Comment by glew02** [comment]
Hi orpiske, Thanks for your response. When looking at the folder where the connector's jars are, camel-util-3.18.2.jar is in there.

Here is the list of them:
```
README.md					   camel-core-languages-3.18.2.jar			     camel-kamelet-3.18.2.jar	      camel-vm-3.18.2.jar	      jackson-dataformat-avro-2.13.3.jar	kotlin-reflect-1.3.20.jar
annotations-13.0.jar				   camel-core-model-3.18.2.jar				     camel-language-3.18.2.jar	      camel-xml-io-util-3.18.2.jar    jackson-datatype-jdk8-2.10.2.jar		kotlin-stdlib-1.3.20.jar
apicurio-registry-common-1.3.2.Final.jar	   camel-core-processor-3.18.2.jar			     camel-log-3.18.2.jar	      camel-xml-jaxb-3.18.2.jar       jakarta.activation-1.2.2.jar		kotlin-stdlib-common-1.3.20.jar
apicurio-registry-rest-client-1.3.2.Final.jar	   camel-core-reifier-3.18.2.jar			     camel-main-3.18.2.jar	      camel-xml-jaxp-3.18.2.jar       jakarta.activation-api-1.2.2.jar		lz4-java-1.7.1.jar
apicurio-registry-utils-converter-1.3.2.Final.jar  camel-dataformat-3.18.2.jar				     camel-management-api-3.18.2.jar  camel-xpath-3.18.2.jar	      jakarta.xml.bind-api-2.3.3.jar		medeia-validator-core-1.1.1.jar
apicurio-registry-utils-serde-1.3.2.Final.jar	   camel-dataset-3.18.2.jar				     camel-mock-3.18.2.jar	      camel-xslt-3.18.2.jar	      javax.activation-1.2.0.jar		medeia-validator-jackson-1.1.1.jar
avro-1.11.0.jar					   camel-direct-3.18.2.jar				     camel-ref-3.18.2.jar	      common-utils-7.1.0.jar	      javax.annotation-api-1.3.2.jar		okhttp-3.14.9.jar
camel-api-3.18.2.jar				   camel-directvm-3.18.2.jar				     camel-rest-3.18.2.jar	      commons-codec-1.15.jar	      javax.servlet-api-3.1.0.jar		okio-1.17.2.jar
camel-attachments-3.18.2.jar			   camel-file-3.18.2.jar				     camel-saga-3.18.2.jar	      commons-compress-1.21.jar       jaxb-core-2.3.0.jar			protobuf-java-3.13.0.jar
camel-base-3.18.2.jar				   camel-health-3.18.2.jar				     camel-scheduler-3.18.2.jar       commons-logging-1.2.jar	      jaxb-impl-2.3.3.jar			retrofit-2.9.0.jar
camel-base-engine-3.18.2.jar			   camel-http-3.18.2.jar				     camel-seda-3.18.2.jar	      connect-json-2.6.0.jar	      jboss-jaxrs-api_2.1_spec-2.0.1.Final.jar	slf4j-api-1.7.36.jar
camel-bean-3.18.2.jar				   camel-http-base-3.18.2.jar				     camel-stub-3.18.2.jar	      converter-jackson-2.9.0.jar     jctools-core-3.3.0.jar			snappy-java-1.1.8.1.jar
camel-browse-3.18.2.jar				   camel-http-common-3.18.2.jar				     camel-support-3.18.2.jar	      guava-20.0.jar		      kafka-avro-serializer-7.1.0.jar		swagger-annotations-2.1.10.jar
camel-cloud-3.18.2.jar				   camel-https-kafka-connector-3.18.2.jar		     camel-timer-3.18.2.jar	      httpclient-4.5.13.jar	      kafka-clients-2.8.0.jar			zstd-jni-1.4.9-1.jar
camel-cluster-3.18.2.jar			   camel-https-kafka-connector-extended-3.18.2-SNAPSHOT.jar  camel-tooling-model-3.18.2.jar   httpcore-4.4.15.jar	      kafka-connect-avro-converter-7.1.0.jar
camel-controlbus-3.18.2.jar			   camel-jackson-3.18.2.jar				     camel-util-3.18.2.jar	      jackson-annotations-2.13.3.jar  kafka-connect-avro-data-7.1.0.jar
camel-core-3.18.2.jar				   camel-kafka-3.18.2.jar				     camel-util-json-3.18.2.jar       jackson-core-2.13.3.jar	      kafka-schema-registry-client-7.1.0.jar
camel-core-engine-3.18.2.jar			   camel-kafka-connector-3.18.2.jar			     camel-validator-3.18.2.jar       jackson-databind-2.13.3.jar     kafka-schema-serializer-7.1.0.jar
```

**Comment by glew02** [comment]
I was running two older versions of other camel connectors. That probably caused a java path issue for which jar to use. I no longer get the error when setting the camel-util to 3.18.2 for the other two older camel connectors.
