### ISSUE TITLE
[ERROR] DynamoDB sink connector - default credential provider with environment variables not working

### ISSUE THREAD

**Issue by jaehyeon-kim** [apache/camel-kafka-connector#1533]
Hello,

I tried to start the dynamodb sink connector with the `useDefaultCredentialsProvider` option to be set to true. However it fails with the following error. (I didn't see an error when I set it to false)

```
[2023-05-25 21:13:19,600] ERROR WorkerSinkTask{id=order-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:190)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:610)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:330)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.connect.errors.ConnectException: Exchange delivery has failed!
	at org.apache.camel.kafkaconnector.CamelSinkTask.put(CamelSinkTask.java:210)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:582)
	... 10 more
Caused by: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[B5193615771A1AD-0000000000000000]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
	at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:597)
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
	at org.apache.camel.processor.SendDynamicProcessor.process(SendDynamicProcessor.java:170)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:477)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:189)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:61)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:182)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:399)
	at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:96)
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:214)
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor$1.process(SharedCamelInternalProcessor.java:111)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:108)
	at org.apache.camel.support.cache.DefaultProducerCache.send(DefaultProducerCache.java:199)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:176)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:148)
	at org.apache.camel.kafkaconnector.CamelSinkTask.put(CamelSinkTask.java:205)
	... 11 more
Caused by: java.lang.NoClassDefFoundError: software/amazon/awssdk/utils/cache/CachedSupplier$StaleValueBehavior
	at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider.<init>(InstanceProfileCredentialsProvider.java:110)
	at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider.<init>(InstanceProfileCredentialsProvider.java:59)
	at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider$BuilderImpl.build(InstanceProfileCredentialsProvider.java:377)
	at software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider.lambda$createChain$0(DefaultCredentialsProvider.java:104)
	at software.amazon.awssdk.utils.Lazy.getValue(Lazy.java:50)
	at software.amazon.awssdk.auth.credentials.internal.LazyAwsCredentialsProvider.resolveCredentials(LazyAwsCredentialsProvider.java:45)
	at software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider.resolveCredentials(DefaultCredentialsProvider.java:123)
	at software.amazon.awssdk.awscore.internal.AwsExecutionContextBuilder.resolveCredentials(AwsExecutionContextBuilder.java:184)
	at software.amazon.awssdk.awscore.internal.AwsExecutionContextBuilder.invokeInterceptorsAndCreateExecutionContext(AwsExecutionContextBuilder.java:120)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.invokeInterceptorsAndCreateExecutionContext(AwsSyncClientHandler.java:69)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:78)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:175)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.dynamodb.DefaultDynamoDbClient.describeTable(DefaultDynamoDbClient.java:2229)
	at org.apache.camel.component.aws2.ddb.Ddb2Endpoint.doStart(Ddb2Endpoint.java:92)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
	at org.apache.camel.impl.engine.AbstractCamelContext.deferStartService(AbstractCamelContext.java:1677)
	at org.apache.camel.impl.engine.AbstractCamelContext.deferStartService(AbstractCamelContext.java:1654)
	at org.apache.camel.impl.engine.AbstractCamelContext.internalAddService(AbstractCamelContext.java:1556)
	at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1498)
	at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1493)
	at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1488)
	at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:969)
	at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:867)
	at org.apache.camel.support.CamelContextHelper.resolveEndpoint(CamelContextHelper.java:123)
	at org.apache.camel.reifier.SendReifier.resolveEndpoint(SendReifier.java:45)
	at org.apache.camel.reifier.SendReifier.createProcessor(SendReifier.java:37)
	at org.apache.camel.reifier.ProcessorReifier.makeProcessor(ProcessorReifier.java:847)
	at org.apache.camel.reifier.ProcessorReifier.addRoutes(ProcessorReifier.java:588)
	at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:237)
	at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:75)
	at org.apache.camel.impl.DefaultModelReifierFactory.createRoute(DefaultModelReifierFactory.java:49)
	at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:862)
	at org.apache.camel.impl.DefaultModel.addRouteDefinitions(DefaultModel.java:189)
	at org.apache.camel.impl.DefaultModel.addRouteDefinition(DefaultModel.java:195)
	at org.apache.camel.impl.DefaultModel.addRouteFromTemplate(DefaultModel.java:428)
	at org.apache.camel.impl.DefaultModel.addRouteFromTemplate(DefaultModel.java:307)
	at org.apache.camel.impl.DefaultCamelContext.addRouteFromTemplate(DefaultCamelContext.java:448)
	at org.apache.camel.component.kamelet.KameletComponent$LifecycleHandler.createRouteForEndpoint(KameletComponent.java:409)
	at org.apache.camel.component.kamelet.KameletComponent$LifecycleHandler.track(KameletComponent.java:448)
	at org.apache.camel.component.kamelet.KameletComponent$1.doInit(KameletComponent.java:160)
	at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
	at org.apache.camel.support.service.ServiceHelper.initService(ServiceHelper.java:84)
	at org.apache.camel.impl.engine.AbstractCamelContext.internalAddService(AbstractCamelContext.java:1553)
	at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1498)
	at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1493)
	at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1488)
	at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:969)
	at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:876)
	at org.apache.camel.support.CamelContextHelper.getMandatoryEndpoint(CamelContextHelper.java:73)
	at org.apache.camel.support.ExchangeHelper.resolveEndpoint(ExchangeHelper.java:122)
	at org.apache.camel.support.ExchangeHelper.resolveEndpoint(ExchangeHelper.java:101)
	at org.apache.camel.processor.SendDynamicProcessor.resolveEndpoint(SendDynamicProcessor.java:296)
	at org.apache.camel.processor.SendDynamicProcessor.process(SendDynamicProcessor.java:157)
	... 25 more
Caused by: java.lang.ClassNotFoundException: software.amazon.awssdk.utils.cache.CachedSupplier$StaleValueBehavior
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 82 more
```

Below shows the connector config.

```
{
  "name": "order-sink",
  "config": {
    "connector.class": "org.apache.camel.kafkaconnector.awsddbsink.CamelAwsddbsinkSinkConnector",
    "tasks.max": "1",
    "key.converter": "org.apache.kafka.connect.json.JsonConverter",
    "key.converter.schemas.enable": false,
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": false,
    "topics": "order",
    "camel.kamelet.aws-ddb-sink.table": "orders-short",
    "camel.kamelet.aws-ddb-sink.region": "ap-southeast-2",
    "camel.kamelet.aws-ddb-sink.operation": "PutItem",
    "camel.kamelet.aws-ddb-sink.writeCapacity": 1,
    "camel.kamelet.aws-ddb-sink.useDefaultCredentialsProvider": true
  }
}
```

When creating it, the following environment variables are set.
* AWS_ACCESS_KEY_ID
* AWS_SECRET_ACCESS_KEY
* AWS_SESSION_TOKEN

Can you please inform how to fix the issue?

Cheers,
Jaehyeon

**Comment by oscerd** [comment]
Did you try the same with AWS credentials file in your user home? I do think there's something wrong in your environment

**Comment by jaehyeon-kim** [comment]
Hi @oscerd 

As I indicated in an earlier issue (https://github.com/apache/camel-kafka-connector/issues/1532), I tried with the option to false and it works fine. The following is the connector config for it.

```
{
  "name": "order-sink",
  "config": {
    "connector.class": "org.apache.camel.kafkaconnector.awsddbsink.CamelAwsddbsinkSinkConnector",
    "tasks.max": "1",
    "key.converter": "org.apache.kafka.connect.json.JsonConverter",
    "key.converter.schemas.enable": false,
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": false,
    "topics": "order",
    "camel.kamelet.aws-ddb-sink.table": "orders-short",
    "camel.kamelet.aws-ddb-sink.region": "ap-southeast-2",
    "camel.kamelet.aws-ddb-sink.operation": "PutItem",
    "camel.kamelet.aws-ddb-sink.writeCapacity": 1,
    "camel.kamelet.aws-ddb-sink.useDefaultCredentialsProvider": false,
    "camel.kamelet.aws-ddb-sink.accessKey": "accessKey",
    "camel.kamelet.aws-ddb-sink.secretKey": "secretKey"
  }
}
```

**Comment by jaehyeon-kim** [comment]
Is it releated to https://github.com/apache/camel-kafka-connector/issues/1331? I don't see dynamodb sink in the fix - https://github.com/apache/camel-kamelets/issues/735

![image](https://github.com/apache/camel-kafka-connector/assets/1023748/16a1bf9b-a5bd-46af-8aea-026a0f2a0d46)

**Comment by oscerd** [comment]
What is the version of the connector you're using?

**Comment by jaehyeon-kim** [comment]
I'm using 3.18.2. Here are the list of files.

```
LICENSE.txt                                        camel-direct-3.18.2.jar            camel-xml-jaxb-3.18.2.jar                 json-utils-2.17.250.jar
NOTICE.txt                                         camel-directvm-3.18.2.jar          camel-xml-jaxp-3.18.2.jar                 kotlin-reflect-1.3.20.jar
README.adoc                                        camel-dsl-support-3.18.2.jar       camel-xpath-3.18.2.jar                    kotlin-stdlib-1.3.20.jar
annotations-13.0.jar                               camel-file-3.18.2.jar              camel-xslt-3.18.2.jar                     kotlin-stdlib-common-1.3.20.jar
annotations-2.17.223.jar                           camel-health-3.18.2.jar            camel-yaml-dsl-3.18.2.jar                 medeia-validator-core-1.1.1.jar
apache-client-2.17.250.jar                         camel-jackson-3.18.2.jar           camel-yaml-dsl-common-3.18.2.jar          medeia-validator-jackson-1.1.1.jar
apicurio-registry-common-1.3.2.Final.jar           camel-jackson-avro-3.18.2.jar      camel-yaml-dsl-deserializers-3.18.2.jar   metrics-spi-2.17.250.jar
apicurio-registry-rest-client-1.3.2.Final.jar      camel-jackson-protobuf-3.18.2.jar  commons-codec-1.15.jar                    netty-buffer-4.1.79.Final.jar
apicurio-registry-utils-converter-1.3.2.Final.jar  camel-kafka-3.18.2.jar             commons-compress-1.21.jar                 netty-codec-4.1.79.Final.jar
apicurio-registry-utils-serde-1.3.2.Final.jar      camel-kafka-connector-3.18.2.jar   commons-logging-1.2.jar                   netty-codec-http-4.1.79.Final.jar
auth-2.17.250.jar                                  camel-kamelet-3.18.2.jar           connect-json-2.6.0.jar                    netty-codec-http2-4.1.79.Final.jar
avro-1.11.0.jar                                    camel-kamelets-utils-0.9.1.jar     converter-jackson-2.9.0.jar               netty-common-4.1.79.Final.jar
aws-core-2.17.250.jar                              camel-language-3.18.2.jar          dynamodb-2.17.250.jar                     netty-handler-4.1.79.Final.jar
aws-json-protocol-2.17.250.jar                     camel-log-3.18.2.jar               eventstream-1.0.1.jar                     netty-nio-client-2.17.250.jar
camel-api-3.18.2.jar                               camel-main-3.18.2.jar              http-client-spi-2.17.250.jar              netty-resolver-4.1.79.Final.jar
camel-aws-ddb-sink-kafka-connector-3.18.2.jar      camel-management-api-3.18.2.jar    httpclient-4.5.13.jar                     netty-transport-4.1.79.Final.jar
camel-aws2-ddb-3.18.2.jar                          camel-mock-3.18.2.jar              httpcore-4.4.15.jar                       netty-transport-classes-epoll-4.1.79.Final.jar
camel-base-3.18.2.jar                              camel-ref-3.18.2.jar               jackson-annotations-2.13.3.jar            netty-transport-native-unix-common-4.1.79.Final.jar
camel-base-engine-3.18.2.jar                       camel-rest-3.18.2.jar              jackson-core-2.13.3.jar                   okhttp-3.14.9.jar
camel-bean-3.18.2.jar                              camel-saga-3.18.2.jar              jackson-databind-2.13.3.jar               okio-1.17.2.jar
camel-browse-3.18.2.jar                            camel-scheduler-3.18.2.jar         jackson-dataformat-avro-2.13.3.jar        profiles-2.17.250.jar
camel-cluster-3.18.2.jar                           camel-seda-3.18.2.jar              jackson-dataformat-protobuf-2.13.3.jar    protobuf-java-3.13.0.jar
camel-controlbus-3.18.2.jar                        camel-stub-3.18.2.jar              jackson-datatype-jdk8-2.10.2.jar          protocol-core-2.17.250.jar
camel-core-3.18.2.jar                              camel-support-3.18.2.jar           jakarta.activation-1.2.2.jar              protoparser-4.0.3.jar
camel-core-engine-3.18.2.jar                       camel-timer-3.18.2.jar             jakarta.activation-api-1.2.2.jar          reactive-streams-1.0.3.jar
camel-core-languages-3.18.2.jar                    camel-tooling-model-3.18.2.jar     jakarta.xml.bind-api-2.3.3.jar            regions-2.17.250.jar
camel-core-model-3.18.2.jar                        camel-util-3.18.2.jar              javax.annotation-api-1.3.2.jar            retrofit-2.9.0.jar
camel-core-processor-3.18.2.jar                    camel-util-json-3.18.2.jar         jaxb-core-2.3.0.jar                       sdk-core-2.17.250.jar
camel-core-reifier-3.18.2.jar                      camel-validator-3.18.2.jar         jaxb-impl-2.3.3.jar                       snakeyaml-engine-2.3.jar
camel-dataformat-3.18.2.jar                        camel-vm-3.18.2.jar                jboss-jaxrs-api_2.1_spec-2.0.1.Final.jar  third-party-jackson-core-2.17.250.jar
camel-dataset-3.18.2.jar                           camel-xml-io-util-3.18.2.jar       jctools-core-3.3.0.jar                    utils-2.17.223.jar
```

**Comment by oscerd** [comment]
It should work in 3.18.2 because the underline kamelets catalog is 0.9.1

https://github.com/apache/camel-kamelets/blob/v0.9.1/kamelets/aws-ddb-sink.kamelet.yaml

My suggestion is to try with 3.20.3

**Comment by jaehyeon-kim** [comment]
Thank you @oscerd! Let me try that out.

**Comment by jaehyeon-kim** [comment]
It works with 3.20.3. Thank you @oscerd!
