### ISSUE TITLE
Camel-elasticsearch-rest-kafka-connector throws java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager

### ISSUE THREAD

**Issue by alessandromonguzzi** [apache/camel-kafka-connector#259]
Download camel-elasticsearch-rest-kafka-connector from https://repo1.maven.org/maven2/org/apache/camel/kafkaconnector/camel-elasticsearch-rest-kafka-connector/0.2.0/camel-elasticsearch-rest-kafka-connector-0.2.0-package.zip 
The log4j2 dependencies are missing and they cause NoClassDefFoundError when the connector is used.

To reproduce it with Strimzi follow these steps:
1. Start Kafka broker cluster
2. Start KafkaConnectS2I cluster
3. Prepare the connector plugin and start a new KafkaConnectS2I build:
```
mkdir connectors
curl https://repo1.maven.org/maven2/org/apache/camel/kafkaconnector/camel-elasticsearch-rest-kafka-connector/0.2.0/camel-elasticsearch-rest-kafka-connector-0.2.0-package.zip > connectors/file.zip
unzip -d connectors file.zip
rm connectors/file.zip
oc start-build my-connect-cluster-connect --from-dir=./connectors --follow
```
Similar things can be done on local installation.

When the connector is firstly invoked, the following error occurs:
```
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
	at org.elasticsearch.rest.BytesRestResponse.<clinit>(BytesRestResponse.java:120)
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1727)
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1704)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1467)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1424)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1394)
	at org.elasticsearch.client.RestHighLevelClient.index(RestHighLevelClient.java:836)
	at org.apache.camel.component.elasticsearch.ElasticsearchProducer.process(ElasticsearchProducer.java:169)
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:67)
	... 28 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 37 more
```
In attach the full log file:
[my-connect-cluster-connect-2-cc4nf-my-connect-cluster-connect.log](https://github.com/apache/camel-kafka-connector/files/4746196/my-connect-cluster-connect-2-cc4nf-my-connect-cluster-connect.log)

**Comment by valdar** [comment]
Hello, thanks for the detailed report.

Can you pleas add `org.slf4j:log4j-over-slf4j:jar:1.7.30` jar (i.e. https://repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar) to `connectors/camel-elasticsearch-rest-kafka-connector/` before running the s2i build and see if it makes any difference?

**Comment by alessandromonguzzi** [comment]
Hi, I retested with the log4j-over-slf4j jar above and the issue is no more reproduced.

**Comment by valdar** [comment]
Ok good to know! Then I will go on with including that jar in the dependencies. Thanks a lot for the issue and the time to follow this through.
