### ISSUE TITLE
Nullpointer exception at org.apache.camel.component.aws2.s3.AWS2S3Producer.processSingleOp

### ISSUE THREAD

**Issue by saranyaeu2987** [apache/camel-kafka-connector#299]
My kafkaconnect stopped after encountering Null pointer exception in middle of message consumption. 
Any guidance on what could caused this issue. Attached full log for reference??
[container (8).log](https://github.com/apache/camel-kafka-connector/files/4827868/container.8.log)

```2020-06-24 20:35:38,219 ERROR WorkerSinkTask{id=heb-s3-emd-dt-temp2-connector-1} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask) [task-thread-heb-s3-emd-dt-temp2-connector-1] 
2020-06-24 20:35:38,219 INFO Stopping CamelSinkTask connector task (org.apache.camel.kafkaconnector.CamelSinkTask) [task-thread-heb-s3-emd-dt-temp2-connector-1] 
2020-06-24 20:35:38,220 INFO Stopping CamelContext (org.apache.camel.kafkaconnector.utils.CamelMainSupport) [task-thread-heb-s3-emd-dt-temp2-connector-1] 
2020-06-24 20:35:38,235 ERROR Failed delivery for (MessageId: ID-emd-kafka-cluster-connect-84565897d6-js7ds-1593030122609-9-300 on ExchangeId: ID-emd-kafka-cluster-connect-84565897d6-js7ds-1593030122609-9-300). Exhausted after delivery attempt: 1 caught: java.lang.NullPointerException 
 
Message History (complete message history is disabled) 
--------------------------------------------------------------------------------------------------------------------------------------- 
RouteId              ProcessorId          Processor                                                                        Elapsed (ms) 
[route8            ] [route8            ] [                                                                              ] [         6] 
	... 
[route8            ] [toD2              ] [aws2-s3://heb-stg-emd-store-raw-ora.pemd?keyName=emd-dt-temp/${date:now:yyyy-M] [         0] 
 
Stacktrace 
--------------------------------------------------------------------------------------------------------------------------------------- (org.apache.camel.processor.errorhandler.DefaultErrorHandler) [task-thread-heb-s3-emd-dt-temp2-connector-6] 
java.lang.NullPointerException 
	at org.apache.camel.component.aws2.s3.AWS2S3Producer.processSingleOp(AWS2S3Producer.java:303) 
	at org.apache.camel.component.aws2.s3.AWS2S3Producer.process(AWS2S3Producer.java:91) 
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:67) 
	at org.apache.camel.processor.SendDynamicProcessor.lambda$process$0(SendDynamicProcessor.java:197) 
	at org.apache.camel.impl.engine.DefaultProducerCache.doInAsyncProducer(DefaultProducerCache.java:309) 
	at org.apache.camel.processor.SendDynamicProcessor.process(SendDynamicProcessor.java:182) 
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:395) 
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:148) 
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:60) 
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:147) 
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:286) 
	at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:66) 
	at org.apache.camel.processor.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:212) 
	at org.apache.camel.processor.SharedCamelInternalProcessor$1.process(SharedCamelInternalProcessor.j

```

The below error causes k8s pod to restart and causing duplicate messages in S3

**Comment by oscerd** [comment]
It seems an empty body

**Comment by saranyaeu2987** [comment]
@oscerd 
Do you mean empty message in a topic? Can a producer send an empty message to a topic?

**Comment by oscerd** [comment]
It seems you have a mixed classpath or something like that.
https://github.com/apache/camel/blob/camel-3.2.0/components/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Producer.java#L303

At line 303 I see just this. Also don't use tasksMax equal to 10, this will create 10 routes, distributed mode for this connector is actually not supported, so leave it at 1.

**Comment by saranyaeu2987** [comment]
Sink Connector  is running slow. It took 40 min to consume 5k message if
tasksmax=10. Extremely slow if tasksmax =1.

**Comment by saranyaeu2987** [comment]
Messages are simple json size < 1kb. Any suggestions how to speed up connector with tasksmax=1 ?

**Comment by oscerd** [comment]
The connector is always based on the component, an optimization could be done in the component, but you've to deal with S3 anyway. This project is still under active development, so there is always space for improvements and you're welcome to contribute.

**Comment by saranyaeu2987** [comment]
By component do you mean aws2-s3 component. ?
Do you have any component which support distributed mode? I would like to
take a look for reference

**Comment by oscerd** [comment]
AWS2-S3 component, yes. 

Distributed mode is currently not supported. We are still looking at it.
