### ISSUE TITLE
flaky syslog integration test 

### ISSUE THREAD

**Issue by valdar** [apache/camel-kafka-connector#367]
see https://github.com/apache/camel-kafka-connector/runs/958385239?check_suite_focus=true

**Comment by orpiske** [comment]
I am also seeing this one fail from time to time on Github. Never on my desktop, but rather frequently on GH.

**Comment by orpiske** [comment]
Using the burn in script, I managed to reproduce this after some time. 

```2020-08-16 17:45:05,438 [ClientTCPWorker] TRACE org.apache.camel.component.netty.NettyProducer - Exception caught at Channel: [id: 0x017e223f, L:/127.0.0.1:47634 - R:localhost/127.0.0.1:49152]         
java.net.PortUnreachableException: null                                                                                                                                                                  
        at sun.nio.ch.DatagramChannelImpl.receive0(Native Method) ~[?:?]                                                                                                                                 
        at sun.nio.ch.DatagramChannelImpl.receiveIntoNativeBuffer(DatagramChannelImpl.java:491) ~[?:?]                                                                                                   
        at sun.nio.ch.DatagramChannelImpl.receive(DatagramChannelImpl.java:469) ~[?:?]                                                                                                                   
        at sun.nio.ch.DatagramChannelImpl.receive(DatagramChannelImpl.java:419) ~[?:?]                                                                                                                   
        at io.netty.channel.socket.nio.NioDatagramChannel.doReadMessages(NioDatagramChannel.java:252) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]                                                   
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75) [netty-transport-4.1.50.Final.jar:4.1.50.Final]                                       
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.50.Final.jar:4.1.50.Final]                                                                   
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-transport-4.1.50.Final.jar:4.1.50.Final]                                                         
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-transport-4.1.50.Final.jar:4.1.50.Final]                                                                  
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.50.Final.jar:4.1.50.Final]                                                                                  
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.50.Final.jar:4.1.50.Final]                                                     
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.50.Final.jar:4.1.50.Final]                                                                        
        at java.lang.Thread.run(Thread.java:834) [?:?]                                                                                                                                                   
2020-08-16 17:45:05,453 [ClientTCPWorker] DEBUG org.apache.camel.component.netty.NettyProducer - Closing channel as an exception was thrown from Netty                                                   
java.net.PortUnreachableException: null                                                                                                                                                                  
        at sun.nio.ch.DatagramChannelImpl.receive0(Native Method) ~[?:?]                                                                                                                                 
        at sun.nio.ch.DatagramChannelImpl.receiveIntoNativeBuffer(DatagramChannelImpl.java:491) ~[?:?]                                                                                                   
        at sun.nio.ch.DatagramChannelImpl.receive(DatagramChannelImpl.java:469) ~[?:?]                                                                                                                   
        at sun.nio.ch.DatagramChannelImpl.receive(DatagramChannelImpl.java:419) ~[?:?]                                                                                                                   
        at io.netty.channel.socket.nio.NioDatagramChannel.doReadMessages(NioDatagramChannel.java:252) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]                                                   
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75) [netty-transport-4.1.50.Final.jar:4.1.50.Final]                                       
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.50.Final.jar:4.1.50.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
