### ISSUE TITLE
Error with Syslog Source Connector

### ISSUE THREAD

**Issue by vbbhatia14** [apache/camel-kafka-connector#665]
Hi,

I tried the below and got the error as : hostname can't be null even though I had provided a host. Tried with both localhost and 0.0.0.0 as in doc. Even tested with an external host as well. Maybe it points to a different hostname property.

**My CamelSyslogSourceConnector.properties values below:**

name=CamelSyslogSourceConnector
connector.class=org.apache.camel.kafkaconnector.syslog.CamelSyslogSourceConnector
tasks.max=1

key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter
topics=syslog
camel.source.path.protocol=udp
camel.source.path.host=**0.0.0.0**
camel.source.path.port=514

**The error stacktrace:**

[2020-11-03 21:14:33,407] ERROR Error starting CamelContext (camel-1) due to exception thrown: hostname can't be null (org.apache.camel.impl.engine.AbstractCamelContext:2674)
java.lang.IllegalArgumentException: hostname can't be null
        at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149)
        at java.net.InetSocketAddress.<init>(InetSocketAddress.java:216)
        at org.apache.camel.component.netty.SingleTCPNettyServerBootstrapFactory.startServerBootstrap(SingleTCPNettyServerBootstrapFactory.java:184)
        at org.apache.camel.component.netty.SingleTCPNettyServerBootstrapFactory.doStart(SingleTCPNettyServerBootstrapFactory.java:113)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:115)
        at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:84)
        at org.apache.camel.component.netty.NettyConsumer.doStart(NettyConsumer.java:75)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:115)
        at org.apache.camel.impl.engine.AbstractCamelContext.startService(AbstractCamelContext.java:3056)
        at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartOrResumeRouteConsumers(InternalRouteStartupManager.java:362)
        at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartRouteConsumers(InternalRouteStartupManager.java:282)
        at org.apache.camel.impl.engine.InternalRouteStartupManager.safelyStartRouteServices(InternalRouteStartupManager.java:181)
        at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartOrResumeRoutes(InternalRouteStartupManager.java:115)
        at org.apache.camel.impl.engine.AbstractCamelContext.doStartCamel(AbstractCamelContext.java:2837)
        at org.apache.camel.impl.engine.AbstractCamelContext.doStartContext(AbstractCamelContext.java:2666)
        at org.apache.camel.impl.engine.AbstractCamelContext.doStart(AbstractCamelContext.java:2629)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:115)
        at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2395)
        at org.apache.camel.main.SimpleMain.doStart(SimpleMain.java:43)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:115)
        at org.apache.camel.kafkaconnector.CamelSourceTask.start(CamelSourceTask.java:115)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:213)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by valdar** [comment]
@vbbhatia14 what version of the connector did you use?

**Comment by vbbhatia14** [comment]
@valdar I am using 0.6 version.

**Comment by tadayosi** [comment]
This should be fixed with 0.9.0. @vbbhatia14 Can you please check it once 0.9.0 is released?  Thanks.

**Comment by valdar** [comment]
@vbbhatia14 `0.9.0` is out now if you want to try it.

**Comment by valdar** [comment]
@vbbhatia14 I am closing this because I am pretty sure it is fixed, feel free to reopen it if needed.
