### ISSUE TITLE
Camel Kafka Connector Catalog throws NPE on Windows

### ISSUE THREAD

**Issue by apupier** [apache/camel-kafka-connector#697]
see https://github.com/camel-tooling/camel-lsp-client-vscode/issues/472

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at org.apache.camel.kafkaconnector.catalog.CamelKafkaConnectorCatalog.initCatalog(CamelKafkaConnectorCatalog.java:65)
	at org.apache.camel.kafkaconnector.catalog.CamelKafkaConnectorCatalog.<init>(CamelKafkaConnectorCatalog.java:52)
	at com.github.cameltooling.lsp.internal.catalog.util.CamelKafkaConnectorCatalogManager.<init>(CamelKafkaConnectorCatalogManager.java:23)
	at com.github.cameltooling.lsp.internal.CamelTextDocumentService.<init>(CamelTextDocumentService.java:94)
	at com.github.cameltooling.lsp.internal.CamelLanguageServer.<init>(CamelLanguageServer.java:53)
	at com.github.cameltooling.lsp.internal.Runner.main(Runner.java:65)
	... 8 more
[Info  - 11:24:59 am] Connection to server got closed. Server will restart.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at org.apache.camel.kafkaconnector.catalog.CamelKafkaConnectorCatalog.initCatalog(CamelKafkaConnectorCatalog.java:65)
	at org.apache.camel.kafkaconnector.catalog.CamelKafkaConnectorCatalog.<init>(CamelKafkaConnectorCatalog.java:52)
	at com.github.cameltooling.lsp.internal.catalog.util.CamelKafkaConnectorCatalogManager.<init>(CamelKafkaConnectorCatalogManager.java:23)
	at com.github.cameltooling.lsp.internal.CamelTextDocumentService.<init>(CamelTextDocumentService.java:94)
	at com.github.cameltooling.lsp.internal.CamelLanguageServer.<init>(CamelLanguageServer.java:53)
	at com.github.cameltooling.lsp.internal.Runner.main(Runner.java:65)
	... 8 more
[Error - 11:25:01 am] Connection to server got closed. Server will not be restarted.
```

**Comment by oscerd** [comment]
This should be fixed.
