### ISSUE TITLE
Getting some error logs for camel.connector 3.1.0 with strimzi 0.20.0 update

### ISSUE THREAD

**Issue by ruchirvaninasdaq** [apache/camel-kafka-connector#766]
Hello, 

We have updated the kafka cluster to strimzi 0.20.0 version and I am seeing that all my connectors (s3 connectors) started printing this error. 

```
Dec 07, 2020 10:48:09 PM org.apache.kafka.connect.runtime.rest.errors.ConnectExceptionMapper toResponse
SEVERE: Uncaught exception in REST call to /admin/loggers/
javax.ws.rs.NotFoundException: HTTP 404 Not Found
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:250)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:679)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:505)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
        at java.lang.Thread.run(Thread.java:748)
```

I am running camel connector version 3.1.0 I have updated the connector to add few more headers for my specific purpose. 
It has been working with 0.16, 0.19 strimzi release. The connector is working as expected (processing data and pushing to kafka) but just posting these error logs. 

Do I need to upgrade camel-connector version to latest (3.6.0)? or is there any settings I can use in current camel (3.1.0) to diable this api calls.

**Comment by oscerd** [comment]
Are you using the camel component version 3.1.0? Or are you using the camel connector from camel-kafka-connector? It's not clear, there is no connectors with version 3.1.0 or 3.6.0, btw the suggestion is to upgrade to the latest version

**Comment by ruchirvaninasdaq** [comment]
Sorry, For the confusion. I am using connector version `0.0.1-SNAPSHOT` and camel component version `3.1.0`. Do have any idea why are these errors showing up?

**Comment by oscerd** [comment]
You don't need the camel component if you use the new release

**Comment by oscerd** [comment]
The connector are now packaged as zip

**Comment by oscerd** [comment]
By the way use a released version not a snapshot

**Comment by ruchirvaninasdaq** [comment]
Yeah, I am trying to upgrade, but we need to upgrade strimzi 0.20 sooner, so is there any way I can fix these errors?

**Comment by ruchirvaninasdaq** [comment]
Yeah, By the time I decided to use the camel-Kafka-connector, there was not stable version, I know repo was saying its not production ready. So its my mistake to use the code. But I want to check with you if you know about this issue. I can try fixing by my own.

**Comment by oscerd** [comment]
The release 0.6.0/0.6.1 has been tested against strimzi 0.20. So the only way I see is upgrading

**Comment by ruchirvaninasdaq** [comment]
Thanks for the information.

**Comment by ruchirvaninasdaq** [comment]
Closing the issue, it had to do with the strimzi image. Thanks for help. 

https://github.com/strimzi/strimzi-kafka-operator/issues/4105
