### ISSUE TITLE
Couchbase dependency missing?

### ISSUE THREAD

**Issue by orpiske** [apache/camel-kafka-connector#878]
Trying to run Couchbase outside of Integration tests and I get this:

```
rg.apache.camel.FailedToCreateProducerException: Failed to create Producer for endpoint: couchbase://http://myhost:11210?bucket=ExampleBucket&username=Administrator&password=xxxxxx&connectTimeout=5000&queryTimeo
ut=5000&producerRetryAttempts=10&producerRetryPause=7500. Reason: java.lang.NoClassDefFoundError: com/couchbase/client/core/retry/RetryStrategy
        at org.apache.camel.support.cache.DefaultProducerCache.acquireProducer(DefaultProducerCache.java:154)
        at org.apache.camel.support.cache.DefaultProducerCache.doInAsyncProducer(DefaultProducerCache.java:282)
        at org.apache.camel.processor.SendDynamicProcessor.process(SendDynamicProcessor.java:180)
        at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:395)
        at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:148)
        at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:60)
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:147)
        at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:312)
        at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:84)
        at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:218)
        at org.apache.camel.impl.engine.SharedCamelInternalProcessor$1.process(SharedCamelInternalProcessor.java:112)
        at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
        at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:109)
        at org.apache.camel.support.cache.DefaultProducerCache.send(DefaultProducerCache.java:189)
        at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:176)
        at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:148)
        at org.apache.camel.kafkaconnector.CamelSinkTask.put(CamelSinkTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:563)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:326)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:229)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: com/couchbase/client/core/retry/RetryStrategy
        at org.apache.camel.component.couchbase.CouchbaseEndpoint.createProducer(CouchbaseEndpoint.java:170)
        at org.apache.camel.support.DefaultEndpoint.createAsyncProducer(DefaultEndpoint.java:203)
        at org.apache.camel.support.cache.ServicePool$SinglePool.acquire(ServicePool.java:212)
        at org.apache.camel.support.cache.ServicePool$SinglePool.acquire(ServicePool.java:196)
        at org.apache.camel.support.cache.ServicePool.acquire(ServicePool.java:112)
        at org.apache.camel.support.cache.DefaultProducerCache.acquireProducer(DefaultProducerCache.java:125)
        ... 27 more
Caused by: java.lang.ClassNotFoundException: com.couchbase.client.core.retry.RetryStrategy
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 33 more
```

It seems that `com.couchbase.client:java-client:3.1.0` is missing from the package zip.

**Comment by oscerd** [comment]
Weird, we need to double check the component

**Comment by oscerd** [comment]
I think this is fixed.

**Comment by oscerd** [comment]
@orpiske can you open a backport PR for 0.7.x? so this will be ok for 0.7.1 too

**Comment by orpiske** [comment]
> @orpiske can you open a backport PR for 0.7.x? so this will be ok for 0.7.1 too

Yes I can. I'll open one soon

**Comment by oscerd** [comment]
Thanks a lot
